version: '3'

services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app:/app:ro
      - ./server/default.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    build: ./app/
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html:ro

  db:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=ahjo2iethaichu5Sheru"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0-init.sql:ro
      - ./db/tracking-data.sql:/docker-entrypoint-initdb.d/1-data.sql:ro
