version: '3.7'

services:
  cache:
    image: varnish:6.3
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - numtonce
    ports:
      - "80:80"
    volumes:
      - ./cache/default.vcl:/etc/varnish/default.vcl:ro
  
  server:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - numtonce
    volumes:
      - ./app:/app:ro
      - ./server/default.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    image: php:7.3-fpm-alpine
    restart: unless-stopped
    networks:
      - numtonce
    volumes:
      - ./app:/var/www/html:ro

networks:
  numtonce:
    name: numtonce
