version: '3.7'

services:  
  app:
    build: ./app/
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - "FLAG=flag{ca$$h_ov3rfl0w}"
      - "REDIS_HOST=db"

  db:
    image: redis:alpine
    restart: unless-stopped
